-- AlterTable
ALTER TABLE "AnnualVax" ALTER COLUMN "age" SET DATA TYPE TEXT,
ALTER COLUMN "weight" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "MedicalHx" ALTER COLUMN "age" SET DATA TYPE TEXT,
ALTER COLUMN "weight" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "PrimaryVax" ALTER COLUMN "age" SET DATA TYPE TEXT,
ALTER COLUMN "weight" SET DATA TYPE TEXT;
